name: scvi-env
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - expat=2.6.4
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nb_conda_kernels=2.5.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.4.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=11.1.0
  - pip=25.0
  - pysocks=1.7.1
  - python=3.12.8
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiobotocore==2.20.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiohttp-retry==2.9.1
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - amqp==5.3.1
      - anndata==0.11.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.10.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - asyncssh==2.20.0
      - atpublic==5.1
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.1
      - billiard==4.2.1
      - biopython==1.85
      - biothings-client==0.4.1
      - bleach==6.2.0
      - boto3==1.36.23
      - botocore==1.36.23
      - captum==0.8.0
      - celery==5.5.1
      - cellxgene-census==1.17.0
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - chex==0.1.88
      - click==8.1.8
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - comm==0.2.2
      - configobj==5.0.9
      - contourpy==1.3.1
      - coverage==7.6.10
      - cryptography==44.0.2
      - cycler==0.12.1
      - dask==2024.7.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docrep==0.3.2
      - dpath==2.2.0
      - dulwich==0.22.8
      - dvc==3.59.1
      - dvc-data==3.16.9
      - dvc-http==2.32.0
      - dvc-objects==5.1.0
      - dvc-render==1.0.2
      - dvc-s3==3.2.0
      - dvc-studio-client==0.21.0
      - dvc-task==0.40.2
      - entrypoints==0.4
      - etils==1.11.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - flatten-dict==0.4.2
      - flax==0.10.2
      - flufl-lock==8.1.0
      - fonttools==4.55.8
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - funcy==2.0
      - future==1.0.0
      - genomepy==0.16.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grandalf==0.8
      - grpcio==1.70.0
      - gto==1.7.2
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - humanize==4.11.0
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - identify==2.6.6
      - idna==3.10
      - igraph==0.11.8
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.32.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - iterative-telemetry==0.0.10
      - jax==0.4.35
      - jaxlib==0.4.35
      - jedi==0.19.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - kombu==5.5.2
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - llvmlite==0.44.0
      - locket==1.0.0
      - loguru==0.7.3
      - loompy==3.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.1
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - mygene==3.2.2
      - mysql-connector-python==9.2.0
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nodeenv==1.9.1
      - norns==0.1.6
      - nose==1.3.7
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.4
      - numpy-groupies==0.11.2
      - numpyro==0.16.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.1
      - orjson==3.10.16
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pathspec==0.12.1
      - patsy==1.0.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - plottable==0.1.5
      - pluggy==1.5.0
      - pooch==1.8.2
      - pre-commit==4.1.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py4j==0.10.9.9
      - pyarrow==19.0.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==3.0.4
      - pyfaidx==0.8.1.3
      - pygit2==1.17.0
      - pygments==2.19.1
      - pygtrie==2.5.0
      - pymde==0.1.18
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==8.3.4
      - pytest-pretty==1.2.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pyzmq==26.2.1
      - ray==2.41.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - s3fs==2025.2.0
      - s3transfer==0.11.2
      - scanpy==1.10.4
      - scib-metrics==0.5.3
      - scikit-learn==1.6.1
      - scikit-misc==0.5.1
      - scipy==1.15.1
      - scmrepo==3.3.10
      - scvi-tools==1.3.1
      - seaborn==0.13.2
      - semver==3.0.4
      - send2trash==1.8.3
      - sentry-sdk==2.22.0
      - session-info==1.0.0
      - setproctitle==1.3.5
      - shap==0.47.1
      - shapely==2.1.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - simplejson==3.19.3
      - six==1.17.0
      - slicer==0.0.8
      - smmap==5.0.2
      - sniffio==1.3.1
      - somacore==1.0.28
      - soupsieve==2.6
      - sparse==0.15.5
      - sqltrie==0.11.2
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorstore==0.1.71
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tiledbsoma==1.16.1
      - tinycss2==1.4.0
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.6.0
      - torchmetrics==1.6.1
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.2.0
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.2
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - vine==5.1.0
      - virtualenv==20.29.1
      - voluptuous==0.15.2
      - wandb==0.19.7
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xarray==2025.1.2
      - yarl==1.18.3
      - zc-lockfile==3.0.post1
      - zipp==3.21.0
prefix: /gpfs/commons/home/svaidyanathan/miniconda3/envs/scvi-env
