name: scvi-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312hb553811_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.2.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h5861a67_2
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.2=h32b1619_0
  - ca-certificates=2024.8.30=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312hf857d28_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.7=py312h5861a67_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.29.0=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jax=0.4.34=pyhd8ed1ab_0
  - jaxlib=0.4.34=cpu_py312h2d9848c_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312hb401068_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - krb5=1.21.3=h37d8d59_0
  - libabseil=20240722.0=cxx17_hac325c4_1
  - libblas=3.9.0=25_osx64_openblas
  - libcblas=3.9.0=25_osx64_openblas
  - libcxx=19.1.3=hf95d169_0
  - libedit=3.1.20191231=h0678c8f_2
  - libexpat=2.6.3=hac325c4_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libgrpc=1.65.5=hb88832f_0
  - liblapack=3.9.0=25_osx64_openblas
  - libopenblas=0.3.28=openmp_h1e3e198_0
  - libprotobuf=5.27.5=h62b0dff_2
  - libre2-11=2024.07.02=hd530cb8_1
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.47.0=h2f8c449_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.3=hf78d878_0
  - markupsafe=3.0.2=py312hbe3f5e4_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - ml_dtypes=0.5.0=py312h98e817e_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=hf036a51_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - openssl=3.3.2=hd23fc13_0
  - opt-einsum=3.4.0=hd8ed1ab_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py312h3d0f464_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.3.1=py312hab44e94_1
  - pyobjc-framework-cocoa=10.3.1=py312hab44e94_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.7=h8f8b54e_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312hb553811_1
  - pyzmq=26.2.0=py312h1060d5c_3
  - re2=2024.07.02=h2fb0a26_1
  - readline=8.2=h9e318b2_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.1=py312h0d0de52_0
  - scipy=1.14.1=py312h888eae2_1
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py312hb553811_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.5=he4ceba3_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py312h7122b0e_1
  - zstd=1.5.6=h915ae27_0
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - anndata==0.10.9
    - appdirs==1.4.4
    - array-api-compat==1.9.1
    - biopython==1.84
    - biothings-client==0.3.1
    - boto3==1.35.54
    - botocore==1.35.54
    - cfgv==3.4.0
    - chex==0.1.87
    - click==8.1.7
    - cloudpickle==3.1.0
    - colorama==0.4.6
    - contextlib2==21.6.0
    - contourpy==1.3.0
    - coverage==7.6.4
    - cycler==0.12.1
    - diskcache==5.6.3
    - distlib==0.3.9
    - docrep==0.3.2
    - etils==1.10.0
    - filelock==3.16.1
    - flax==0.10.1
    - fonttools==4.54.1
    - frozenlist==1.5.0
    - fsspec==2024.10.0
    - future==1.0.0
    - genomepy==0.16.1
    - grpcio==1.67.1
    - h5py==3.12.1
    - huggingface-hub==0.26.2
    - humanize==4.11.0
    - hyperopt==0.2.7
    - identify==2.6.1
    - iniconfig==2.0.0
    - ipywidgets==8.1.5
    - jmespath==1.0.1
    - joblib==1.4.2
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyterlab==4.2.5
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - legacy-api-wrap==1.4
    - lightning==2.4.0
    - lightning-utilities==0.11.8
    - llvmlite==0.43.0
    - loguru==0.7.2
    - loompy==3.0.7
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.9.2
    - mdurl==0.1.2
    - ml-collections==0.1.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mudata==0.3.1
    - multidict==6.1.0
    - multipledispatch==1.0.0
    - mygene==3.2.2
    - mysql-connector-python==9.1.0
    - natsort==8.4.0
    - networkx==3.4.2
    - nodeenv==1.9.1
    - norns==0.1.6
    - nose==1.3.7
    - notebook==7.2.2
    - numba==0.60.0
    - numpy==1.26.4
    - numpy-groupies==0.11.2
    - numpyro==0.15.3
    - optax==0.2.3
    - orbax-checkpoint==0.8.0
    - pandas==2.2.3
    - patsy==0.5.6
    - pillow==11.0.0
    - pluggy==1.5.0
    - pre-commit==4.0.1
    - propcache==0.2.0
    - protobuf==5.28.3
    - py4j==0.10.9.7
    - pyarrow==18.0.0
    - pyfaidx==0.8.1.3
    - pymde==0.1.18
    - pynndescent==0.5.13
    - pyparsing==3.2.0
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - pytest==8.3.3
    - pytest-pretty==1.2.0
    - pytorch-lightning==2.4.0
    - ray==2.38.0
    - rich==13.9.4
    - s3transfer==0.10.3
    - scanpy==1.10.3
    - scikit-learn==1.5.2
    - scvi-tools==1.2.0
    - seaborn==0.13.2
    - session-info==1.0.0
    - sparse==0.15.4
    - statsmodels==0.14.4
    - stdlib-list==0.11.0
    - sympy==1.13.3
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - tensorstore==0.1.67
    - threadpoolctl==3.5.0
    - toolz==1.0.0
    - torch==2.2.2
    - torchmetrics==1.5.1
    - torchvision==0.17.2
    - tqdm==4.66.6
    - tzdata==2024.2
    - umap-learn==0.5.7
    - virtualenv==20.27.1
    - werkzeug==3.1.2
    - widgetsnbextension==4.0.13
    - xarray==2024.10.0
    - yarl==1.17.1
prefix: /Users/smriti/opt/anaconda3/envs/scvi-env
