_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 12
                - 45
                - 53
                - 54
                - 55
                - 103
                - 105
                - 106
            "2":
                - 1
                - 5
                - 9
                - 12
                - 45
                - 53
                - 54
                - 55
                - 103
                - 105
                - 106
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
accelerator:
    value: auto
adversarial_mixing:
    value: true
batch_size:
    value: 128
check_val_every_n_epoch:
    value: null
datasplitter_kwargs:
    value: null
devices:
    value: auto
early_stopping:
    value: true
eps:
    value: 1e-08
figure_output_dir:
    value: /gpfs/commons/home/svaidyanathan/multi_vi_splice_runs/MultiVISpliceTraining_20250509_121803_job4443556/figures
lr:
    value: 0.0001
max_epochs:
    value: 500
model_save_dir:
    value: /gpfs/commons/home/svaidyanathan/multi_vi_splice_runs/MultiVISpliceTraining_20250509_121803_job4443556/models
mudata_path:
    value: /gpfs/commons/groups/knowles_lab/Karin/Leaflet-analysis-WD/MOUSE_SPLICING_FOUNDATION/MODEL_INPUT/052025/mouse_foundation_data_20250502_155802_ge_splice_combined.h5mu
n_epochs_kl_warmup:
    value: 50
n_latent:
    value: 30
n_steps_kl_warmup:
    value: null
plan_kwargs:
    value: null
save_best:
    value: true
shuffle_set_split:
    value: true
train_size:
    value: null
umap_cell_label:
    value:
        - broad_cell_type
validation_size:
    value: null
weight_decay:
    value: 0.001
